name: 'Consumable Code Pixabay API'
description: 'Retrofit has been Handled, Consumable code for request Public API (Pixabay API)'
author: 'Muhammad Faisal Amir'
inputs:
  myInput:
    description: 'Input to use'
    required: false
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}